# Generated by Django 5.1 on 2024-08-12 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartparking', '0002_alter_reservation_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_new_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='parking',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='smartparking.parking'),
        ),
    ]
