# Generated by Django 5.1 on 2024-08-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartparking', '0003_customuser_is_new_user_alter_reservation_parking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gerant',
            name='parking',
        ),
        migrations.AddField(
            model_name='gerant',
            name='parkings',
            field=models.ManyToManyField(related_name='gerants', to='smartparking.parking'),
        ),
    ]
