# Generated by Django 5.1 on 2024-08-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartparking', '0004_remove_gerant_parking_gerant_parkings'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
