# Generated by Django 5.1 on 2024-08-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartparking', '0006_remove_gerant_parkings_parking_gerant'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('expiree', 'expirée'), ('annulee', 'annulée')], default='active', max_length=25),
        ),
    ]
