# Generated by Django 5.1 on 2024-08-18 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartparking', '0007_reservation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_cancel',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_expired',
        ),
    ]
