# Generated by Django 5.1 on 2024-08-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartparking', '0008_remove_reservation_is_cancel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gerant',
            name='date_embauche',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('expired', 'expirée'), ('cancel', 'annulée')], default='active', max_length=25),
        ),
    ]
