# Generated by Django 5.1 on 2024-08-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartparking', '0011_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='matricule',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
