# Generated by Django 5.1 on 2024-08-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartparking', '0013_alter_matricule_client_alter_reservation_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
