# Generated by Django 5.1 on 2024-09-12 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartparking', '0014_customuser_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntreSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_entree', models.DateTimeField(blank=True, null=True)),
                ('heure_sortie', models.DateTimeField(blank=True, null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrees_sorties', to='smartparking.reservation')),
            ],
        ),
    ]
