# Generated by Django 5.1 on 2024-10-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartparking', '0015_entresortie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntreSortie',
        ),
    ]
